# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('coskewkurtosis_rcpp_hello_world', PACKAGE = 'coskewkurtosis')
}

residualcokurtosisMF <- function(NN, sstockM2, sstockM4, bbetacov) {
    .Call('coskewkurtosis_residualcokurtosisMF', PACKAGE = 'coskewkurtosis', NN, sstockM2, sstockM4, bbetacov)
}

residualcokurtosisSF <- function(sstockM2, sstockM4, mfactorM2, bbeta) {
    .Call('coskewkurtosis_residualcokurtosisSF', PACKAGE = 'coskewkurtosis', sstockM2, sstockM4, mfactorM2, bbeta)
}

